### ISSUE TITLE
OpenBadgeのRecipient検証も行う

### ISSUE THREAD

**Issue by fujie** [block-base/openbadge-vc-converter#12]
OpenBadgeをアップロードするとき、メールアドレスも入力させてRecipient検証も行う。
入力したメールアドレスはVC上にも保持する
VerifierにVCを提示した際に、VC上に保持しているOpenBadgeおよびRecipient情報を元でVerifier側でもOpenBadgeのValidationを実施できるようにする

**Comment by taijusanagi** [comment]
こちらメールアドレスの実装が必要と共有を受けた、上記issueはこちらと重複してたのでcloseし、こちらで管理する
